[package]
name = "irene"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
description = "An equivalence checker for hybrid quantum programs"

[lib]
path = "src/lib.rs"

[features]
rewrite-experiments = ["dep:portmatching", "dep:portgraph"]

[dependencies]
bigdecimal = "0.4"
bitgauss = "0.4.3"
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
num-bigint = "0.4"
num-rational = "0.4"
petgraph = "0.8"
portmatching = { version = "0.3.3", optional = true }
portgraph = { version = "0.8", optional = true }
oq3_lexer = { path = "vendor/openqasm3_parser/crates/oq3_lexer" }
oq3_source_file = { path = "vendor/openqasm3_parser/crates/oq3_source_file" }
oq3_syntax = { path = "vendor/openqasm3_parser/crates/oq3_syntax" }
rug = { version = "1.30", default-features = false, features = ["float", "integer", "std"] }
thiserror = "2.0"
