//! Exact local path sums scheduled by the size of the remaining separator.
//! Tables are over bound coordinates ONLY. Entries are existing exact
//! cyclotomic polynomials in free coordinates, not numerical approximations.
use super::*;
// Bound actual live dense cells rather than rejecting every seven-variable
// factor. This is an allocation guard: each cell owns an exact polynomial.
struct Factor {
    scope: Vec<KernelVariable>,
    entries: Vec<Polynomial>,
}
impl Encoder {
    fn contraction_cells(
        &self,
        width: usize,
        live: usize,
        cofactors: usize,
        stage: &str,
    ) -> Option<usize> {
        let limits = crate::equivalence::tuning::limits();
        let width_limit = if self.coordinates.is_empty() {
            limits.width
        } else {
            limits.width.min(limits.symbolic_width)
        };
        let cells = u32::try_from(width)
            .ok()
            .and_then(|w| 1usize.checked_shl(w));
        let admitted = cells.filter(|&n| {
            width <= width_limit
                && live
                    .checked_add(n)
                    .is_some_and(|total| total <= limits.cells)
                && n.checked_mul(cofactors)
                    .is_some_and(|work| work <= self.work)
        });
        if admitted.is_none() && std::env::var_os("IRENE_DEBUG_AGGREGATE").is_some() {
            eprintln!(
                "contraction refused stage={stage} width={width} width_limit={width_limit} cells={cells:?} live={live} cell_limit={} remaining_work={}",
                limits.cells, self.work
            );
        }
        admitted
    }
    pub(super) fn contract(&mut self, t: &WorkingTerm) -> Option<Polynomial> {
        self.contract_ordered(t, None)
    }
    pub(super) fn contract_ordered(
        &mut self,
        t: &WorkingTerm,
        order: Option<&[KernelVariable]>,
    ) -> Option<Polynomial> {
        if t.paths.iter().any(|v| !v.is_bound_path()) {
            return None;
        }
        let start = std::time::Instant::now();
        let initial = self.work;
        let mut pieces = Vec::new();
        let empty = || WorkingTerm {
            paths: BTreeSet::new(),
            constraints: vec![],
            coefficient: KernelScalar::Rational(integer(1)),
            phase: KernelPhasePolynomial::default(),
        };
        let mut scalar = empty();
        scalar.coefficient = t.coefficient.clone();
        pieces.push(scalar);
        for p in &t.constraints {
            let mut x = empty();
            x.constraints.push(p.clone());
            pieces.push(x);
        }
        for (p, c) in t.phase.selectors() {
            let mut x = empty();
            x.phase.add_boolean(&p, c);
            pieces.push(x);
        }
        let mut tables = Vec::new();
        for piece in pieces {
            let mut vars = BTreeSet::new();
            for p in &piece.constraints {
                vars.extend(p.variables());
            }
            for (p, _) in piece.phase.selectors() {
                vars.extend(p.variables());
            }
            if !scalar_conditions_within_budget(&piece.coefficient, |p| {
                vars.extend(p.variables());
                true
            }) {
                return None;
            }
            let scope: Vec<_> = vars.intersection(&t.paths).cloned().collect();
            let live = tables.iter().map(|f: &Factor| f.entries.len()).sum();
            let cells = self.contraction_cells(scope.len(), live, 1, "initial-factor")?;
            let mut entries = Vec::new();
            for bits in 0..cells {
                self.charge(1)?;
                let mut assigned = piece.clone();
                for (j, v) in scope.iter().enumerate() {
                    assigned.substitute(v, &KernelBooleanPolynomial::from(bits >> j & 1 != 0));
                }
                let entry = self.term(&assigned);
                if entry.is_none() && std::env::var_os("IRENE_DEBUG_AGGREGATE").is_some() {
                    eprintln!(
                        "contraction refused stage=factor-encoding width={} assignment={bits} remaining_work={}",
                        scope.len(),
                        self.work
                    );
                }
                entries.push(entry?);
            }
            tables.push(Factor { scope, entries });
        }
        let mut max_width = 0;
        let mut pending = t.paths.clone();
        while !pending.is_empty() {
            // Estimate the table generated by eliminating each candidate, not
            // its index or circuit origin. Prefer narrow separators, then small
            // coefficient sums; both complete cofactors are still included.
            let v = pending
                .iter()
                .min_by_key(|v| {
                    let selected: Vec<_> = tables.iter().filter(|f| f.scope.contains(v)).collect();
                    let neighbors: BTreeSet<_> = selected
                        .iter()
                        .flat_map(|f| f.scope.iter())
                        .filter(|w| *w != *v)
                        .collect();
                    let atoms: usize = selected
                        .iter()
                        .map(|f| f.entries.iter().map(Vec::len).sum::<usize>())
                        .sum();
                    (
                        order
                            .and_then(|o| o.iter().position(|w| w == *v))
                            .unwrap_or(0),
                        neighbors.len(),
                        atoms,
                    )
                })?
                .clone();
            pending.remove(&v);
            let (selected, mut rest): (Vec<_>, Vec<_>) =
                tables.into_iter().partition(|f| f.scope.contains(&v));
            let scope: Vec<_> = selected
                .iter()
                .flat_map(|f| f.scope.iter())
                .filter(|x| **x != v)
                .cloned()
                .collect::<BTreeSet<_>>()
                .into_iter()
                .collect();
            max_width = max_width.max(scope.len());
            // Selected input tables remain live while the output is built.
            let live = rest.iter().chain(&selected).map(|f| f.entries.len()).sum();
            let cells = self.contraction_cells(scope.len(), live, 2, "separator")?;
            let mut entries = Vec::new();
            for bits in 0..cells {
                let mut sum = Vec::new();
                for bit in [false, true] {
                    self.charge(1)?;
                    let mut product = self.literal(integer(1), 0, false)?;
                    for f in &selected {
                        let mut index = 0;
                        for (j, w) in f.scope.iter().enumerate() {
                            let value = if *w == v {
                                bit
                            } else {
                                bits >> scope.binary_search(w).ok()? & 1 != 0
                            };
                            if value {
                                index |= 1 << j;
                            }
                        }
                        product = self.multiply(product, f.entries[index].clone())?;
                    }
                    sum.extend(product);
                }
                entries.push(self.compact(sum)?);
            }
            rest.push(Factor { scope, entries });
            tables = rest;
        }
        let mut result = self.literal(integer(1), 0, false)?;
        for f in tables {
            if !f.scope.is_empty() {
                return None;
            }
            result = self.multiply(result, f.entries.into_iter().next()?)?;
        }
        if std::env::var_os("IRENE_DEBUG_AGGREGATE").is_some() {
            eprintln!(
                "scheduled contraction paths={} max_boundary={max_width} atoms={} work={} ms={}",
                t.paths.len(),
                result.len(),
                initial - self.work,
                start.elapsed().as_millis()
            );
        }
        Some(result)
    }
}

#[cfg(test)]
#[path = "../../../../tests/unit/equivalence/aggregate/exact_smt/contraction/tests.rs"]
mod tests;
